### ISSUE TITLE
CORS issue of accessing `api.coingecko.com`

### ISSUE THREAD

**Issue by iossocket** [Scaffold-Stark/scaffold-eth-stark#7]
## Issue Overview

In dev environment, run nextjs app locally, will cause CORS issue, when access `https://api.coingecko.com/api/v3/simple/price` endpoint.

## Proposed Solutions or Ideas

Move the api call to nextjs servers side, and in frontend, just access: `/api/price/${symbol}`

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

**Comment by Benjtalkshow** [comment]
Can I work on this issue? ETA is 5hrs

**Comment by Michaelkingsdev** [comment]
Let me work on this issue please. Thanks

**Comment by 0xquantum3labs** [comment]
wouldnt this be an issue on Scaffold-Stark main repo too ?  @iossocket

**Comment by iossocket** [comment]
@0xquantum3labs yes, the main repo had the same issue
